### ISSUE TITLE
Multiplexing

### ISSUE THREAD

**Issue by andreasotto** [vti/sockjs-perl#6]
What do you think about multiplexing support in sockjs-perl? 
I found these both resources interesting to read:
http://www.rabbitmq.com/blog/2012/02/23/how-to-compose-apps-using-websockets/
http://baudehlo.com/2013/05/07/sockjs-multiple-channels-and-why-i-dumped-socket-io/

**Comment by vti** [comment]
Yeah, that's a nice feature. But if I understand it correctly, the second link expains how to do that without changing the server code ;)

**Comment by BlueT** [comment]
I think this can be closed?
